services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: 'rabbitmq'
    ports:
      - 6672:5672
      - 15672:15672
    volumes:
      - /mnt/rabbitmq/data:/var/lib/rabbitmq/
      - /mnt/rabbitmq/log:/var/log/rabbitmq